### ISSUE TITLE
unknown Method xsdbool

### ISSUE THREAD

**Issue by ivanchodelat** [koemaeda/abap-markdown#3]
Method unknown.   **xsdbool**
This method is unknown and it is not possible to activate... Do you know what it refers to ?
~~~
  method _escape.
    output = htmlspecialchars(
      input = text
      ent_html401 = abap_true
      ent_noquotes = allow_quotes
      ent_quotes = xsdbool( allow_quotes is initial ) ).
  endmethod.
~~~

**Comment by larshp** [comment]
`xsdbool` is a built in function from v740sp08, guess in this case you can replace it with `boolc`

**Comment by ivanchodelat** [comment]
Okay, everything's fine.
**v740sp04.**
thank you
